sonar.projectKey=jobbridge
sonar.projectName=JobBridge
sonar.projectVersion=1.0

sonar.sourceEncoding=UTF-8

sonar.sources=server.js,src,js,html,css,database
sonar.tests=test

sonar.exclusions=node_modules/**,data/**,coverage/**,server.*.log,auth_service/.venv/**
sonar.test.inclusions=test/**/*.js